## Coursera assignment 2: Caching the Inverse of a Matrix

## This function creates a special "matrix" object that can cache its inverse.
# It allows one to set, get, setinverse and getinverse of a square matrix
# Here is how to use it
# source("cachematrix.R")
# M <- matrix(rnorm(100),10,10)
# y1 <- makeCacheMatrix(M)  ## alternatively:  y1 <- makeCacheMatrix(); y1$set(M)
# ## y1$get() # allows you to see the value of original vector
# ## y1$set() # allows you to set the value
# ## y1$setinverse # allows you to set the inverse calculated elsewhere (should be cacheSolve)
# ## y1$getinverse # allows you to see the inverse 
makeCacheMatrix <- function(x = matrix()) {
    m <- NULL
    set <- function(y) {
        x <<- y
        m <<- NULL
    }
    
    get <- function() x
    setinverse <- function(inverse) m <<- inverse
    getinverse <- function() m
    
    list(set=set, get=get, 
         setinverse=setinverse, getinverse=getinverse)
}



## This function computes the inverse of the special "matrix" returned by makeCacheMatrix above. 
# If the inverse has already been calculated (and the matrix has not changed), then cacheSolve should retrieve the inverse from the cache.
# cacheSolve take in an objecte generated by makeCacheMatrix
# if mean never calculated before, then calc it.  
# example: 
# result <- cacheSolve(y1) # will see if inverse is null.  If so, it will retrieve vector by $get(), calc inverse, and store the value using setinverse
cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    m <- x$getinverse()
    if(!is.null(m)){
        message("getting cached data")
        return(m)
    }
    data <- x$get()
    m <- solve(data, ...)
    x$setinverse(m)
    m
}
